#define DEFAULT_ROWS 100
#define DEFAULT_COLS 100

#define DEFAULT_NUM_OBSRACLES 100
#define DEFAULT_NUM_PREDATORS 500
#define DEFAULT_NUM_PREY 500
#define DEFAULT_NUM_ITERATOINS 50

#define DEFAULT_IMAGE '-'
#define DEFAULT_PREY_IMAGE 'f'
#define DEFAULT_PRDATOR_IMAGE 'S'
#define DEFAULT_OBSTACLE_IMAGE '#'

#define TIME_TO_FEED 6
#define TIME_TO_REPRODUCE 6